name: Dr. Amir's Assignment Feedback

on: [push, pull_request]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc

      - name: Compile, Build, Link for individual tests
        run: |
          gcc -o first first.c
          gcc -o second second.c

      - uses: WCU-CS-CooperLab/autofeedback-s@v1.6
        id: autograder
        continue-on-error: true

      - uses: ebrain-lab/split-by@master
        id: split
        with:
          string: "${{ steps.autograder.outputs.points }}"
          split-by: "/"

      # make dir for badges
      - name: badges branch and make dir
        run: |
          git checkout badges 2>/dev/null || git checkout -b badges
          mkdir -p .github/badges
      # make points badge
      - name: points badge
        uses: emibcn/badge-action@v2.0.2
        id: pbadge
        with:
          label: "Tests Passed"
          status: ${{ steps.autograder.outputs.points }}
          color: ${{
            steps.split.outputs._0 > 3 && 'green'               ||
            steps.split.outputs._0 > 19 && 'yellow,green' ||
            steps.split.outputs._0 > 2 && 'yellow,yellow,green' ||
            steps.split.outputs._0 > 1 && 'orange,yellow,yellow'  ||
            steps.split.outputs._0 > 0 && 'orange,orange,yellow'  ||
            'red' }}
          path: ".github/badges/points.svg"

      - name: Upload badge as artifact
        uses: actions/upload-artifact@v4
        with:
          name: badge
          path: ".github/badges/points.svg"
          if-no-files-found: error

      # commit and push badge if score has changed
      - name: Commit badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '.github/badges/points.svg'
          git commit -m "Add/Update badge"
        continue-on-error: true
      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: badges
          force: true
      - name: not enough pass
        if: steps.split.outputs._0 <= 3
        run: echo "${{ steps.split.outputs._0 }} tests passed out of ${{steps.split.outputs._1}} is fewer than 2 passed tests, Check Annotations for feedback. " && exit 1
      - name: enough pass
        if: steps.split.outputs._0 > 3
        run: echo "${{ steps.split.outputs._0 }} tests passed out of ${{steps.split.outputs._1}}, Check Annotations for feedback. "
